version: "3.3"
services:
  reverseproxy:
    image: reverseproxy
    ports:
      - 8081:8081
      - 8080:8080
    restart: always
    nginx:
      depends_on:
        - reverseproxy
      image: reverseproxy
      restart: always